name: Release

on:
  push:
    tags:
      - 'v[0-3].*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: darwin
            arch: amd64
            suffix: darwin-x64
          - os: darwin
            arch: arm64
            suffix: darwin-arm64
          - os: linux
            arch: amd64
            suffix: linux-x64
          - os: linux
            arch: arm64
            suffix: linux-arm64
          - os: windows
            arch: amd64
            suffix: windows-x64.exe
          - os: windows
            arch: arm64
            suffix: windows-arm64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          mkdir -p dist
          go build -o "dist/codepacker-${{ matrix.suffix }}" -ldflags="-s -w"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.suffix }}
          path: dist/*
          retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: binaries-*
          merge-multiple: true

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          draft: false
          prerelease: false
          generate_release_notes: true 